# Generated by Django 3.0.7 on 2020-06-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supercategory', '0002_auto_20200608_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
