# Generated by Django 3.0.7 on 2020-06-08 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supercategory', '0001_initial'),
        ('subcategory', '0004_auto_20200608_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='super',
            field=models.ForeignKey(limit_choices_to={'parent_name'}, on_delete=django.db.models.deletion.CASCADE, to='supercategory.Supercategory'),
        ),
    ]
