# Generated by Django 3.0.7 on 2020-06-08 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supercategory', '0002_auto_20200608_2027'),
        ('subcategory', '0007_auto_20200608_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='super',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercategory.Supercategory'),
        ),
    ]
