# Generated by Django 3.0.7 on 2020-06-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='logo',
            field=models.ImageField(upload_to='beneficiary/'),
        ),
    ]
