# Generated by Django 3.0.7 on 2020-06-08 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiary', '0005_auto_20200608_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('needed_amount', models.IntegerField()),
                ('approved', models.IntegerField()),
                ('ben', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiary.Beneficiary')),
            ],
            options={
                'db_table': 'cases',
                'managed': True,
            },
        ),
    ]
