# Generated by Django 3.0.7 on 2020-06-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cases',
            options={'managed': True, 'verbose_name': 'case', 'verbose_name_plural': 'cases'},
        ),
    ]
