# Generated by Django 3.0.7 on 2020-06-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategoryfeatures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategoryfeatures',
            options={'managed': True, 'verbose_name': 'SubcategoryFeature', 'verbose_name_plural': 'SubcategoryFeatures'},
        ),
    ]
