# Generated by Django 3.0.7 on 2020-06-08 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'managed': True, 'verbose_name': 'beneficiary', 'verbose_name_plural': 'beneficiaries'},
        ),
    ]
