# Generated by Django 3.0.7 on 2020-06-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0002_auto_20200608_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='address',
            field=models.CharField(max_length=255, verbose_name='beneficiary address'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='martial_status',
            field=models.CharField(max_length=8, verbose_name='beneficiary status'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='name',
            field=models.CharField(max_length=255, verbose_name='beneficiary name'),
        ),
    ]
