# Generated by Django 3.0.7 on 2020-06-08 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0004_auto_20200608_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
