from django.urls import path
from . import views


urlpatterns = [
    path('',views.all_programs),
    path('development',views.development),
    path('economic_support',views.economic_support),
    path('medical',views.medical),
    path('social_support',views.social_support),
    path('zakat',views.zakat),
    path('medical/addiction',views.addiction),
    path('medical/tumor',views.tumor),
    path('medical/babies',views.babies),
    path('medical/blind',views.blind),
    path('medical/accident_burns',views.accident_burns),
    path('medical/virus_c',views.virus_c),
    path('medical/cancer',views.cancer),
    path('medical/heart',views.heart),
    path('medical/kidny',views.kidny),
    path('medical/ray',views.ray),
    path('medical/special_people',views.special_people),
    path('medical/surgery',views.surgery),
    path('medical/treatment',views.treatment),
    path('medical/artificial_limps',views.artificial_limps),
    path('social_support/children',views.children),
    path('social_support/blind_diseas',views.blind_diseas),
    path('social_support/food',views.food),
    path('social_support/deptors',views.deptors),
    path('social_support/old_people',views.old_people),
    path('social_support/clothes',views.clothes),
    path('social_support/orphans_marriage',views.orphans_marriage),
    path('social_support/orphans',views.orphans),
    path('economic_support/cow',views.cow),
    path('economic_support/good_loan',views.good_loan),
    path('economic_support/jop',views.jop),
    path('economic_support/charity_project',views.charity_project),
    path('development/water',views.water),
    path('development/house',views.house),

    ]
